set(_CATKIN_CURRENT_PACKAGE "perception")
set(perception_VERSION "0.0.0")
set(perception_MAINTAINER "team4 <team4@todo.todo>")
set(perception_PACKAGE_FORMAT "2")
set(perception_BUILD_DEPENDS "roscpp" "rospy" "pcl_ros" "sensor_msgs" "tf" "rosbag")
set(perception_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "pcl_ros" "sensor_msgs" "tf" "rosbag")
set(perception_BUILDTOOL_DEPENDS "catkin")
set(perception_BUILDTOOL_EXPORT_DEPENDS )
set(perception_EXEC_DEPENDS "roscpp" "rospy" "pcl_ros" "sensor_msgs" "tf" "rosbag")
set(perception_RUN_DEPENDS "roscpp" "rospy" "pcl_ros" "sensor_msgs" "tf" "rosbag")
set(perception_TEST_DEPENDS )
set(perception_DOC_DEPENDS )
set(perception_DEPRECATED "")